site_name: JS Hand Book

site_description: This book helps to understand the core concepts of JavaScript.

site_author: H.R. Mohan Ram

repo_url: https://github.com/mohanramphp/javascript-hand-book

pages:
    - Introduction: index.md
    - About Author: about/about.md
    - License: license/license.md


theme:
  name: 'material'

